### PR TITLE
Support scuttlebutt 5.5.20

### PR DESCRIPTION
**Pull request by dolphin278**
Support changes on 'update' event arguments (key, value, source
-> change, timestamp, source).

All tests passed. 

I did not bump version, since I don't know whether you use semver or not.

### CODE REVIEW

**Comment by juliangruber** [comment]
cool! Can you write documentation for it too?

**Comment by dolphin278** [comment]
I surely will, if we decide what is need to be described — basically, there was only one change in index.js to handle new 'update' event format that was changed in scuttlebutt. Other changes are in tests only, where tests were listening for 'update' event. So from the point of view of the user of `authoritee` nothing changes at all, as far as I can see (if we agree that current set of tests is sufficient).

**Comment by juliangruber** [comment]
oh, nice, I see!

**Comment by juliangruber** [comment]
published as 0.0.2, thanks man!

**Comment by dolphin278** [comment]
Thank you for great module ;)

---

Boris Egorov
skype/gtalk/nickname: dolphin278
mobile: +7 905 728 1543

**Pull request merged**
